language: php

php:
  - 8.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer update --no-interaction --prefer-dist
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit

